// @ts-nocheck
export const CANON = [
  { id: 1, slug: 'first-song', title: 'The First Song', act: 1, relicLabel: 'First Sound', symbol: 'I', color: '#38BDF8', weapon: 'Breath', scriptureRef: 'Genesis 1:2', scriptureText: 'The Spirit of God was hovering over the waters.', hook: 'Where silence became song.', purpose: 'The breath came before the song.', testimonyMoment: 'I had no song. I had a sigh.', description: 'Breathed at 3:12am.', cinematicScene: 'Single light in dark valley.', sound: 'Piano + breath', artwork: '', audio: '', youtube: '', lyrics: '', reflection: ['Where am I sitting in silence that God calls incubation?','Am I waiting for God to move or recognizing He already hovers?','What would breath before breakthrough look like?'], action: 'Spend 5 minutes in silence. Inhale: Holy Spirit. Exhale: Breathe again.' },
  { id: 2, slug: 'stormbreak', title: 'Stormbreak', act: 1, relicLabel: 'Stormbreaker', symbol: 'II', color: '#6366F1', weapon: 'Hammer', scriptureRef: 'Psalm 29:3', scriptureText: 'The voice of the Lord is over the waters.', hook: 'The voice of the LORD thunders.', purpose: 'The storm did not break me. It announced me.', testimonyMoment: 'God did not calm storm, He became it.', description: 'Night storm broke inside.', cinematicScene: 'Wolf on cliff, lightning.', sound: 'Trailer drums + rain', artwork: '', audio: '', youtube: '', lyrics: '', reflection: ['What storm am I praying away that God wants to announce me with?'], action: 'Worship before the thunder stops.' },
  { id: 3, slug: 'awakening', title: 'Awakening', act: 1, relicLabel: 'Awakened Eyes', symbol: 'III', color: '#F59E0B', weapon: 'Eyes', scriptureRef: 'Ephesians 1:18', scriptureText: 'Eyes of your heart enlightened.', hook: 'Eyes opened from death to light.', purpose: 'Not forgotten, hidden for formation.', testimonyMoment: 'God was not late.', description: 'Hidden not forgotten.', cinematicScene: 'Dawn through forest.', sound: 'Strings + vocal', artwork: '', audio: '', youtube: '', lyrics: '', reflection: ['Where has hiddenness been protecting me?'], action: 'Ask: What are You forming in hidden?' },
  { id: 4, slug: 'ashes-to-altar', title: 'Ashes to Altar', act: 1, relicLabel: 'Ashen Crown', symbol: 'IV', color: '#57534E', weapon: 'Crown', scriptureRef: 'Isaiah 61:3', scriptureText: 'Beauty for ashes.', hook: 'Beauty from ashes, altar from ruin.', purpose: 'What I called ending, God called altar.', testimonyMoment: 'Ashes still smelled like smoke when God called beautiful.', description: 'End was altar.', cinematicScene: 'Ash crown to gold.', sound: 'Minor piano', artwork: '', audio: '', youtube: '', lyrics: '', reflection: ['What ashes do I call ruin that God calls altar?'], action: 'Lay ashes down as offering today.' },
  { id: 5, slug: 'fire-forged', title: 'Fire Forged', act: 2, relicLabel: 'Fire Forged', symbol: 'V', color: '#EF4444', weapon: 'Forge Hammer', scriptureRef: '1 Peter 1:7', scriptureText: 'Faith refined by fire.', hook: 'Faith refined like gold.', purpose: 'Fire reveals what is eternal.', testimonyMoment: 'Fire named me.', description: 'Forged when quitting easier.', cinematicScene: 'Blade glowing in forge.', sound: 'Industrial rock', artwork: '', audio: '', youtube: '', lyrics: '', reflection: ['What fire reveals, not destroys?'], action: 'Thank God for fire today.' },
  { id: 6, slug: 'healing-tide', title: 'Healing Tide', act: 2, relicLabel: 'Healing Mantle', symbol: 'VI', color: '#06B6D4', weapon: 'Mantle', scriptureRef: 'Psalm 147:3', scriptureText: 'He heals brokenhearted.', hook: 'He heals brokenhearted.', purpose: 'Healing was starting line.', testimonyMoment: 'Doctor said one thing. Word said another.', description: 'Healing impossible.', cinematicScene: 'Tide washing wounds at sunrise.', sound: 'Ambient + waves', artwork: '', audio: '', youtube: '', lyrics: '', reflection: ['Where does healing need to be starting line?'], action: 'Let tide wash one wound today.' },
  { id: 7, slug: 'wolf-fang', title: 'Wolf Fang', act: 2, relicLabel: 'Wolf Fang', symbol: 'VII', color: '#E5E7EB', weapon: 'Fang', scriptureRef: 'Joel 2:25', scriptureText: 'I will restore years locusts ate.', hook: 'What storm stole, God restored.', purpose: 'Mark became weapon.', testimonyMoment: 'God gave back.', description: 'Identity restored.', cinematicScene: 'Fang catching light.', sound: 'Tribal drums', artwork: '', audio: '', youtube: '', lyrics: '', reflection: ['What have locusts eaten?'], action: 'Declare restoration over stolen years.' },
  { id: 8, slug: 'identity-restored', title: 'Identity Restored', act: 2, relicLabel: 'Seal of Sonship', symbol: 'VIII', color: '#FACC15', weapon: 'Seal', scriptureRef: '1 Peter 2:9', scriptureText: 'Chosen generation, royal priesthood.', hook: 'From orphan to chosen.', purpose: 'Fight FROM identity, not FOR it.', testimonyMoment: 'I am who He says I am.', description: 'Fight FROM.', cinematicScene: 'Robe exchange.', sound: 'Orchestral', artwork: '', audio: '', youtube: '', lyrics: '', reflection: ['Where am I fighting FOR not FROM?'], action: 'Wear seal today, not shame.' },
  { id: 9, slug: 'lions-roar', title: "Lion's Roar", act: 3, relicLabel: "Lion's Roar", symbol: 'IX', color: '#D97706', weapon: 'Roar', scriptureRef: 'Revelation 5:5', scriptureText: 'Lion of tribe of Judah triumphed.', hook: 'Lion has triumphed.', purpose: 'One roar silenced thousand lies.', testimonyMoment: 'Fought with mouth — worship.', description: 'One roar.', cinematicScene: 'Lion roaring battlefield.', sound: 'War anthem', artwork: '', audio: '', youtube: '', lyrics: '', reflection: ['What lie needs one roar?'], action: 'Roar worship over one lie today.' },
  { id: 10, slug: 'wolf-blade', title: 'Wolf Blade', act: 3, relicLabel: 'Wolf Blade', symbol: 'X', color: '#F59E0B', weapon: 'Blade', scriptureRef: 'Hebrews 4:12', scriptureText: 'Word alive, sharper than sword.', hook: 'Wolf = identity. Blade = Word.', purpose: 'Weapon was in His Word.', testimonyMoment: 'Blade forged night I wanted to quit.', description: 'Endurance.', cinematicScene: 'Blade cooling in snow.', sound: 'Metal worship', artwork: '', audio: '', youtube: '', lyrics: '', reflection: ['What verse is my blade?'], action: 'Carry one verse as blade today.' },
  { id: 11, slug: 'thunder-drums', title: 'Thunder Drums', act: 3, relicLabel: 'Thunder Drums', symbol: 'XI', color: '#7C3AED', weapon: 'Drums', scriptureRef: 'Psalm 29:3', scriptureText: 'God of glory thunders.', hook: 'Thunder breaks cedars.', purpose: 'Every hit broke chain.', testimonyMoment: 'Drummed to shift atmosphere.', description: 'Praise percussion.', cinematicScene: 'Drums on mountain.', sound: 'Taiko', artwork: '', audio: '', youtube: '', lyrics: '', reflection: ['What atmosphere needs shift?'], action: 'Drum praise 2 minutes today.' },
  { id: 12, slug: 'war-cry', title: 'War Cry', act: 3, relicLabel: 'War Cry', symbol: 'XII', color: '#DC2626', weapon: 'Shofar', scriptureRef: '2 Corinthians 10:4', scriptureText: 'Weapons mighty in God.', hook: 'Weapons mighty in God.', purpose: 'Shouted before wall fell.', testimonyMoment: 'Shouted before.', description: 'Sound before breakthrough.', cinematicScene: 'Army worshiping before battle.', sound: 'Shofar', artwork: '', audio: '', youtube: '', lyrics: '', reflection: ['Where shout before wall falls?'], action: 'Shout before you see victory.' },
  { id: 13, slug: 'spirit-mantle', title: 'Spirit Mantle', act: 4, relicLabel: 'Spirit Mantle', symbol: 'XIII', color: '#10B981', weapon: 'Mantle', scriptureRef: '1 John 2:27', scriptureText: 'Anointing remains in you.', hook: 'Anointing remains.', purpose: 'Oil flows from crushing.', testimonyMoment: 'Oil from crushing.', description: 'Pressed secret.', cinematicScene: 'Mantle, oil dripping.', sound: 'Pad + choir', artwork: '', audio: '', youtube: '', lyrics: '', reflection: ['Where striving not abiding?'], action: 'Remain 10 min today.' },
  { id: 14, slug: 'tower-of-one', title: 'Tower of One', act: 4, relicLabel: 'Tower of One', symbol: 'XIV', color: '#0EA5E9', weapon: 'Watchtower', scriptureRef: 'Psalm 61:2', scriptureText: 'Lead me to rock higher than I.', hook: 'Babel to Pentecost.', purpose: 'Called higher to see farther.', testimonyMoment: 'Called to tower.', description: 'Self to Kingdom.', cinematicScene: 'Lone tower light.', sound: 'Piano -> orchestra', artwork: '', audio: '', youtube: '', lyrics: '', reflection: ['Where calling higher?'], action: 'Climb higher perspective today.' },
  { id: 15, slug: 'running-wolf', title: 'Running Wolf', act: 4, relicLabel: 'Running Wolf', symbol: 'XV', color: '#A3A3A3', weapon: 'Feet', scriptureRef: 'Isaiah 52:7', scriptureText: 'Beautiful feet bring good news.', hook: 'Beautiful feet messenger.', purpose: 'Healed to run, not hide.', testimonyMoment: 'Healed to run.', description: 'Messenger.', cinematicScene: 'Wolf running ridge with fire.', sound: 'Running percussion', artwork: '', audio: '', youtube: '', lyrics: '', reflection: ['Where healed to run but hiding?'], action: 'Run with fire today.' },
  { id: 16, slug: 'legacy', title: 'Legacy', act: 4, relicLabel: 'Legacy Seal', symbol: 'XVI', color: '#FEF3C7', weapon: 'Arrow', scriptureRef: 'Psalm 127:4', scriptureText: 'Like arrows in hands of warrior.', hook: 'My story ends where theirs begins.', purpose: 'Scars now arrows for next gen.', testimonyMoment: 'My story ends where theirs begins.', description: 'About those after.', cinematicScene: 'Old wolf watching young wolves with torches.', sound: 'Legacy choir', artwork: '', audio: '', youtube: '', lyrics: '', reflection: ['Who runs because I did not quit?'], action: 'Launch one arrow today.' },
]
export const allRelics = CANON
