// @ts-nocheck
export const FOOTER = { text: 'RUNNING WOLF • STORMBREAKERS • 16 SONGS • 16 BATTLES • ONE TESTIMONY • ONE KING' }
export const BIBLE = { FOOTER: 'Every testimony points back to Christ', VERSE: 'Rev 12:11 — They overcame by the blood of the Lamb and the word of their testimony.', COPYRIGHT: '© Running Wolf Stormbreakers — ONE KING' }
export const STYLE = { footer: 'mt-20 pt-8 border-t border-amber-900/20' }

export const CANON = [
  { id: 1, slug: 'first-song', title: 'The First Song', act: 1, relicLabel: 'First Sound', symbol: 'I', color: '#38BDF8', weapon: 'Breath', scriptureRef: 'Genesis 1:2', hook: 'Where silence became song.', testimonyMoment: 'I had no song. I had a sigh.', description: 'Breathed at 3:12am when God broke silence.', cinematicScene: 'Single light in dark valley. Breath visible in cold.', sound: 'Piano + breath', artwork: '/artwork/01-first-song.jpg', audio: '/audio/01-first-song.mp3', youtube: '', lyrics: '' },
  { id: 2, slug: 'stormbreak', title: 'Stormbreak', act: 1, relicLabel: 'Stormbreaker', symbol: 'II', color: '#6366F1', weapon: 'Hammer of Storm', scriptureRef: 'Psalm 29:3', hook: 'The voice of the Lord thunders over waters.', testimonyMoment: 'God did not calm the storm, He became it.', description: 'The night the storm broke inside me.', cinematicScene: 'Wolf on cliff as lightning splits sky.', sound: 'Trailer drums + rain', artwork: '/artwork/02-stormbreak.jpg', audio: '/audio/02-stormbreak.mp3', youtube: '', lyrics: '' },
  { id: 3, slug: 'awakening', title: 'Awakening', act: 1, relicLabel: 'Awakened Eyes', symbol: 'III', color: '#F59E0B', weapon: 'Eyes of Fire', scriptureRef: 'Ephesians 1:18', hook: 'Eyes opened from death to light.', testimonyMoment: 'God was not late. He was preparing.', description: 'Realized I was not forgotten, I was hidden.', cinematicScene: 'Dawn breaking through forest after night.', sound: 'Strings + vocal', artwork: '/artwork/03-awakening.jpg', audio: '/audio/03-awakening.mp3', youtube: '', lyrics: '' },
  { id: 4, slug: 'ashes-to-altar', title: 'Ashes to Altar', act: 1, relicLabel: 'Ashen Crown', symbol: 'IV', color: '#57534E', weapon: 'Crown of Ash', scriptureRef: 'Isaiah 61:3', hook: 'Beauty from ashes, altar from ruin.', testimonyMoment: 'My ashes still smelled like smoke when God called them beautiful.', description: 'What I thought was end was an altar.', cinematicScene: 'Crown of ash turning to gold in hands.', sound: 'Minor piano', artwork: '/artwork/04-ashes-to-altar.jpg', audio: '/audio/04-ashes-to-altar.mp3', youtube: '', lyrics: '' },
  { id: 5, slug: 'fire-forged', title: 'Fire Forged', act: 2, relicLabel: 'Fire Forged', symbol: 'V', color: '#EF4444', weapon: 'Forge Hammer', scriptureRef: '1 Peter 1:7', hook: 'Faith refined like gold in fire.', testimonyMoment: 'Fire did not consume me. It named me.', description: 'Forged when quitting was easier than continuing.', cinematicScene: 'Blade glowing orange in forge, hammer falling.', sound: 'Industrial + anthem rock', artwork: '/artwork/05-fire-forged.jpg', audio: '/audio/05-fire-forged.mp3', youtube: '', lyrics: '' },
  { id: 6, slug: 'healing-tide', title: 'Healing Tide', act: 2, relicLabel: 'Healing Mantle', symbol: 'VI', color: '#06B6D4', weapon: 'Mantle of Healing', scriptureRef: 'Psalm 147:3', hook: 'He heals the brokenhearted.', testimonyMoment: 'Doctor said one thing. Word said another. I chose Word.', description: 'Written in room where healing felt impossible. From healing, not for healing.', cinematicScene: 'Wounds washed by tide at sunrise, footprints in sand.', sound: 'Ambient worship + waves', artwork: '/artwork/06-healing-tide.jpg', audio: '/audio/06-healing-tide.mp3', youtube: '', lyrics: '' },
  { id: 7, slug: 'wolf-fang', title: 'Wolf Fang', act: 2, relicLabel: 'Wolf Fang', symbol: 'VII', color: '#E5E7EB', weapon: 'Fang Dagger', scriptureRef: 'Joel 2:25', hook: 'What the storm stole, God restored.', testimonyMoment: 'God gave back what locusts ate.', description: 'Identity restored. The wolf was not wild — it was wounded.', cinematicScene: 'White wolf standing, fang catching light.', sound: 'Tribal drums + cello', artwork: '/artwork/07-wolf-fang.jpg', audio: '/audio/07-wolf-fang.mp3', youtube: '', lyrics: '' },
  { id: 8, slug: 'identity-restored', title: 'Identity Restored', act: 2, relicLabel: 'Seal of Sonship', symbol: 'VIII', color: '#FACC15', weapon: 'Seal Ring', scriptureRef: '1 Peter 2:9', hook: 'From orphan to chosen.', testimonyMoment: 'I am not what I did. I am who He says I am.', description: 'Stopped fighting FOR identity, started fighting FROM it.', cinematicScene: 'Beggar robe exchanged for royal robe, seal stamped.', sound: 'Orchestral worship', artwork: '/artwork/08-identity-restored.jpg', audio: '/audio/08-identity-restored.mp3', youtube: '', lyrics: '' },
  { id: 9, slug: 'lions-roar', title: "Lion's Roar", act: 3, relicLabel: "Lion's Roar", symbol: 'IX', color: '#D97706', weapon: 'Roar', scriptureRef: 'Revelation 5:5', hook: 'The Lion has triumphed.', testimonyMoment: 'I fought with my mouth — worship.', description: 'One roar from Judah silenced 1000 lies.', cinematicScene: 'Lion roaring over battlefield, enemy fleeing.', sound: 'War anthem + choir', artwork: '/artwork/09-lions-roar.jpg', audio: '/audio/09-lions-roar.mp3', youtube: '', lyrics: '' },
  { id: 10, slug: 'wolf-blade', title: 'Wolf Blade', act: 3, relicLabel: 'Wolf Blade', symbol: 'X', color: '#F59E0B', weapon: 'Wolf Blade — double-edged, fire-tempered', scriptureRef: 'Hebrews 4:12', hook: 'Wolf = identity. Blade = Word.', testimonyMoment: 'Blade forged on night I wanted to quit.', description: 'Song of endurance. When endurance was not a choice.', cinematicScene: 'Blade cooling in snow, steam rising at dawn.', sound: 'Orchestral metal worship', artwork: '/artwork/10-wolf-blade.jpg', audio: '/audio/10-wolf-blade.mp3', youtube: '', lyrics: '' },
  { id: 11, slug: 'thunder-drums', title: 'Thunder Drums', act: 3, relicLabel: 'Thunder Drums', symbol: 'XI', color: '#7C3AED', weapon: 'War Drums — atmosphere shifter', scriptureRef: 'Psalm 29:3', hook: 'The thunder breaks the cedars.', testimonyMoment: 'We drummed to shift atmosphere.', description: 'When praise became percussion. Every hit broke a chain.', cinematicScene: 'War drums on mountain, clouds forming with each hit.', sound: 'Taiko drums + cinematic trailer', artwork: '/artwork/11-thunder-drums.jpg', audio: '/audio/11-thunder-drums.mp3', youtube: '', lyrics: '' },
  { id: 12, slug: 'war-cry', title: 'War Cry', act: 3, relicLabel: 'War Cry', symbol: 'XII', color: '#DC2626', weapon: 'Shofar', scriptureRef: '2 Corinthians 10:4', hook: 'Weapons mighty in God.', testimonyMoment: 'We shouted before wall fell.', description: 'The sound before breakthrough.', cinematicScene: 'Army worshiping before battle, shofar raised.', sound: 'Shofar + electric guitar', artwork: '/artwork/12-war-cry.jpg', audio: '/audio/12-war-cry.mp3', youtube: '', lyrics: '' },
  { id: 13, slug: 'spirit-mantle', title: 'Spirit Mantle', act: 4, relicLabel: 'Spirit Mantle', symbol: 'XIII', color: '#10B981', weapon: 'Mantle — oil that remains', scriptureRef: '1 John 2:27', hook: 'The anointing remains.', testimonyMoment: 'Oil flows from crushing, not striving.', description: 'Anointing pressed in secret place, not stage.', cinematicScene: 'Mantle passing, oil dripping from fringe.', sound: 'Ambient pad + whisper choir', artwork: '/artwork/13-spirit-mantle.jpg', audio: '/audio/13-spirit-mantle.mp3', youtube: '', lyrics: '' },
  { id: 14, slug: 'tower-of-one', title: 'Tower of One', act: 4, relicLabel: 'Tower of One', symbol: 'XIV', color: '#0EA5E9', weapon: 'Watchtower', scriptureRef: 'Psalm 61:2', hook: 'Babel to Pentecost — self to Kingdom.', testimonyMoment: 'Called to tower when everyone left field.', description: 'The biggest storytelling flip — self-building to Kingdom-building.', cinematicScene: 'Lone tower with single light, city below dark.', sound: 'Solo piano -> full orchestra', artwork: '/artwork/14-tower-of-one.jpg', audio: '/audio/14-tower-of-one.mp3', youtube: '', lyrics: '' },
  { id: 15, slug: 'running-wolf', title: 'Running Wolf', act: 4, relicLabel: 'Running Wolf', symbol: 'XV', color: '#A3A3A3', weapon: 'Feet of Wolf — carrier', scriptureRef: 'Isaiah 52:7', hook: 'Beautiful feet of the messenger.', testimonyMoment: 'Healed to run.', description: 'Artist identity becomes messenger. Not running from, running for.', cinematicScene: 'Wolf running across ridge carrying fire in mouth.', sound: 'Running percussion + anthem', artwork: '/artwork/15-running-wolf.jpg', audio: '/audio/15-running-wolf.mp3', youtube: '', lyrics: '' },
  { id: 16, slug: 'legacy', title: 'Legacy', act: 4, relicLabel: 'Legacy Seal', symbol: 'XVI', color: '#FEF3C7', weapon: 'Arrow of Legacy', scriptureRef: 'Psalm 127:4', hook: 'My story ends where theirs begins.', testimonyMoment: 'My story ends where theirs begins.', description: 'Never about me. About those who run after.', cinematicScene: 'Old wolf watching young wolves run with torches into valley.', sound: 'Legacy choir + strings', artwork: '/artwork/16-legacy.jpg', audio: '/audio/16-legacy.mp3', youtube: '', lyrics: '' },
]

export const WORD_CATEGORIES = [
  { id: 'calling', title: 'CALLING', scripture: 'Jer 1:5', anchor: 'Before I formed you I knew you.', explanation: 'Calling is revealed.' },
  { id: 'redemption', title: 'REDEMPTION', scripture: '2 Cor 5:17', anchor: 'New creation.', explanation: 'Every mark becomes testimony.' },
  { id: 'healing', title: 'HEALING', scripture: 'Ps 147:3', anchor: 'He heals brokenhearted.', explanation: 'Forged when impossible.' },
  { id: 'fire', title: 'FIRE', scripture: 'Mal 3:3', anchor: 'He will sit as refiner.', explanation: 'Fire reveals eternal.' },
  { id: 'anointing', title: 'ANOINTING', scripture: '1 Jn 2:27', anchor: 'Anointing remains.', explanation: 'Oil breaks yoke.' },
  { id: 'identity', title: 'IDENTITY', scripture: '1 Pet 2:9', anchor: 'Chosen generation.', explanation: 'Fight FROM identity.' },
  { id: 'warfare', title: 'WARFARE', scripture: '2 Cor 10:4', anchor: 'Weapons mighty in God.', explanation: 'Worship IS warfare.' },
  { id: 'worship', title: 'WORSHIP', scripture: 'Jn 4:24', anchor: 'Spirit and truth.', explanation: 'Ends at His feet. ONE KING.' },
]
export const allRelics = CANON
